# Generated by Django 6.0.5 on 2026-05-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalmodel',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
