# Generated by Django 6.0.5 on 2026-05-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_profesionalmodel_foto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalmodel',
            name='foto_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
