# Generated by Django 5.0.3 on 2026-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_infra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamodel',
            name='asesor_id',
        ),
        migrations.AddField(
            model_name='citamodel',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='citamodel',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citamodel',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='citamodel',
            name='profesional_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='citamodel',
            name='wompi_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='citamodel',
            name='cliente_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='citamodel',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_PAGO', max_length=20),
        ),
        migrations.CreateModel(
            name='HorarioEmpresaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa_id', models.CharField(max_length=36)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'citas_horarios_empresa',
                'unique_together': {('empresa_id', 'dia_semana')},
            },
        ),
    ]
