# Generated by Django 6.0.5 on 2026-05-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_infra', '0002_remove_citamodel_asesor_id_citamodel_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamodel',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada (pendiente de pago)'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20),
        ),
    ]
