# Generated by Django 6.0.5 on 2026-05-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_infra', '0003_estado_programada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioempresamodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='citamodel',
            name='sede_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='horarioempresamodel',
            name='sede_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='horarioempresamodel',
            unique_together={('empresa_id', 'dia_semana', 'sede_id')},
        ),
    ]
