# Generated by Django 5.0.3 on 2026-05-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialModel',
            fields=[
                ('usuario_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'auth_credenciales',
            },
        ),
    ]
