# Generated by Django 6.0.5 on 2026-05-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion_infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialmodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
