# Generated by Django 6.0.5 on 2026-05-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion_infra', '0002_credencialmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialmodel',
            name='rol',
            field=models.CharField(default='empresa', max_length=20),
        ),
    ]
