# Generated by Django 6.0.5 on 2026-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion_infra', '0003_credencialmodel_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetTokenModel',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_password_reset_tokens',
            },
        ),
    ]
