# Generated by Django 5.0.3 on 2026-05-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomodel',
            name='imagen_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
