# Generated by Django 5.0.3 on 2026-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_infra', '0002_serviciomodel_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomodel',
            name='tipo_servicio',
            field=models.CharField(default='CITA', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviciomodel',
            name='duracion_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
