# Generated by Django 6.0.5 on 2026-05-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_infra', '0003_serviciomodel_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomodel',
            name='capacidad_por_slot',
            field=models.IntegerField(default=1),
        ),
    ]
