# Generated by Django 6.0.5 on 2026-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_infra', '0004_serviciomodel_capacidad_por_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomodel',
            name='permite_sesion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviciomodel',
            name='precio_120_dias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciomodel',
            name='precio_30_dias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciomodel',
            name='precio_90_dias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
