# Generated by Django 5.0.3 on 2026-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('publicacion_id', models.CharField(db_index=True, max_length=36)),
                ('usuario_id', models.CharField(max_length=36)),
                ('autor_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('texto', models.TextField()),
                ('padre_id', models.CharField(blank=True, max_length=36, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'publicaciones_comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('publicacion_id', models.CharField(db_index=True, max_length=36)),
                ('usuario_id', models.CharField(max_length=36)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'publicaciones_likes',
                'unique_together': {('publicacion_id', 'usuario_id')},
            },
        ),
    ]
