# Generated by Django 5.0.3 on 2026-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_comentariomodel_likemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionmodel',
            name='imagenes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
