# Generated by Django 5.0.3 on 2026-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicacionmodel_imagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComentarioModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('comentario_id', models.CharField(db_index=True, max_length=36)),
                ('usuario_id', models.CharField(max_length=36)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comentarios_likes',
                'unique_together': {('comentario_id', 'usuario_id')},
            },
        ),
    ]
