# Generated by Django 6.0.5 on 2026-05-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_likecomentariomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariomodel',
            name='padre_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='comentariomodel',
            name='usuario_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='usuario_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
