# Generated by Django 5.0.3 on 2026-05-08 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('color_primario', models.CharField(default='#000000', max_length=7)),
                ('color_secundario', models.CharField(default='#FFFFFF', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresas_saas',
            },
        ),
        migrations.CreateModel(
            name='NoticiaModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='empresas_infra.empresamodel')),
            ],
            options={
                'db_table': 'empresas_noticias',
            },
        ),
    ]
