# Generated by Django 6.0.5 on 2026-05-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='foto_portada_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresamodel',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
