# Generated by Django 6.0.5 on 2026-05-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_infra', '0002_empresamodel_foto_portada_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
