# Generated by Django 5.0.3 on 2026-05-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_infra', '0003_empresamodel_ciudad_empresamodel_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='moneda',
            field=models.CharField(default='COP', max_length=3),
        ),
    ]
