# Generated by Django 6.0.5 on 2026-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_infra', '0004_empresamodel_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
