# Generated by Django 6.0.5 on 2026-05-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_infra', '0005_empresamodel_correo_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='wompi_events_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='wompi_integrity_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='wompi_public_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
