# Generated by Django 6.0.5 on 2026-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_infra', '0006_wompi_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='mensaje_advertencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
