# Generated by Django 6.0.5 on 2026-06-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_infra', '0007_empresamodel_mensaje_advertencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPublicitarioModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('imagen_url', models.TextField()),
                ('link_url', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresas_banners',
            },
        ),
    ]
