# Generated by Django 6.0.5 on 2026-06-05 23:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_infra', '0010_seed_categoria_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresamodel',
            name='rut_archivo',
            field=models.FileField(blank=True, null=True, upload_to='empresas/ruts/'),
        ),
        migrations.AlterField(
            model_name='categoriamodel',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
